namespace MailgunSharp
{
  public enum SmtpErrorCode
  {
    SERVICE_IS_NOT_AVAILABLE = 421,
    MAILBOX_UNAVAILABLE = 450,
    INTERNAL_SERVER_ERROR = 451,
    SERVER_INSUFFICENT_STORAGE = 452,
    SERVER_UNABLE_TO_EXECUTE_COMMAND = 455,
    COMMAND_NOT_RECOGNIZED = 500,
    SYNTAX_ERROR_COMMAND_ARGUMENTS = 501,
    COMMAND_NOT_IMPLEMENTED = 502,
    BAD_SEQUENCE_OF_COMMANDS = 503,
    COMMAND_PARAMETERS_NOT_IMPLEMENTED = 504,
    DUMMY_SERVER_HOST_WONT_ACCEPT = 521,
    MESSAGE_UNDELIVERABLE_POLICY = 541,
    USER_MAILBOX_UNAVAILABLE = 550,
    USER_NOT_ON_SERVER = 551,
    EXCEEDS_STORAGE_ALLOCATION = 552,
    MAILBOX_NAME_INVALID = 553,
    TRANSACTION_FAILED = 554,
    ADDRESS_FORMAT_NOT_RECOGNIZED = 555,
    RECIVING_SERVER_REJECTION_MESSAGE = 556
  }
}
